export const types = {
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    FETCH_MESSAGE: 'FETCH_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
};